apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vote-app-backend
  namespace: vote-app
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: vote-app-backend
  chart:
    spec:
      chart: ./charts/backend
  values:
    cpu: "500m"
